keys:
  - &admin_autophagy age1yubikey1qtks320tydx8myr56yr4cgqx92fynn8eryv6snljzhgp0uhmcwecgh6wnea
  - &server_hindberige age14cg498d2sds8eypzkjg077rfwe9kxxmwpfhyxwzd8cdts5a2f9psjjsvfz
creation_rules:
  - path_regex: secrets/hindberige/[^/]+\.(yaml|env)$
    key_groups:
    - age:
        - *admin_autophagy
        - *server_hindberige
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
        - *admin_autophagy
