# Færeld :: Configuration File
#
# Please see
# https://faereld.readthedocs.io/en/latest/usage/configuration.html for a
# complete reference of configuration options, as well as their effects.

# data_options :: Settings For Data Options
data_options:
  data_path: ~/sandbox/autophagy/hraew/hraew/horda/faereld.hord
  use_wending: true
  num_last_objects: 10

# summary_options :: Settings For Summary Mode
summary_options:
  max_graph_width: 100
  exclude_from_total_time:
  - TSK
  exclude_from_entry_time_distribution:
  - IRL

# project_areas :: Definitions For Project-Specific Areas
#
# Project area definitions should be in the form:
# code:
#   name: Area Name
#   rendering_string: On {date} I worked on {object} for {duration}
#
# See https://faereld.readthedocs.io/en/latest/usage/configuration.html#project-areas
# for more information.
project_areas:
  RES:
    name: Research
    rendering_string: On {date} I worked on {object} ({area_name}) for {duration}
      - {purpose}
  DES:
    name: Design
    rendering_string: On {date} I worked on {object} ({area_name}) for {duration}
      - {purpose}
  DEV:
    name: Development
    rendering_string: On {date} I worked on {object} ({area_name}) for {duration}
      - {purpose}
  DOC:
    name: Documentation
    rendering_string: On {date} I worked on {object} ({area_name}) for {duration}
      - {purpose}
  TST:
    name: Testing
    rendering_string: On {date} I worked on {object} ({area_name}) for {duration}
      - {purpose}

# projects :: Project Object Definitions
#
# A project definition should be of the form
# code:
#   name: Project Name
#   link: <link to project homepage>
#   desc: Project description

projects:
  faereld:
    desc: A time tracking tool.
    link: https://github.com/Autophagy/faereld
    name: Færeld
  insegel:
    desc: A theme for the Sphinx documentation engine.
    link: https://github.com/Autophagy/insegel
    name: Insegel
  datarum:
    desc: A calendar system based on the French Republican Calendar.
    link: https://github.com/Autophagy/datarum
    name: Datárum
  hraew:
    desc: A project information & documentation engine.
    link: https://github.com/Autophagy/hraew
    name: Hrǽw
  scieldas:
    desc: A service to provide metadata badges for Open Source projects.
    link: https://github.com/Autophagy/scieldas
    name: Scieldas
  antimber:
    desc: A set of configuration files for Arch Linux.
    link: https://github.com/Autophagy/antimber
    name: Antimber
  getheode:
    desc: A tool for language construction.
    link: https://github.com/Autophagy/getheode
    name: Geþeóde
  hwaete:
    desc: A project to document my bread baking.
    link: https://github.com/Autophagy/hwaete
    name: Hwǣte
  wisdomhord:
    desc: A flat file database tool for internal project use.
    link: https://github.com/Autophagy/wisdomhord
    name: Wísdómhord
  ametan:
    desc: An Android app for scrum estimation planning poker.
    link: https://github.com/Autophagy/ametan
    name: Ametan
  aerende:
    desc: Post it notes
    link: https://github.com/Autophagy/aerende
    name: Ærende
  black:
    desc: The uncompromising Python code formatter
    link: https://github.com/ambv/black
    name: Black
  regn:
    desc: Weather station
    link: https://github.com/Autophagy/regn
    name: Regn
  tid:
    desc: Cooking tool
    link: https://github.com/autophagy/tid
    name: Tíd
  northanwind:
    desc: Ventilation fan
    name: Norþanwind
  forebodere:
    desc: Discord quote bot
    name: Forebodere
  stypelas:
    desc: Architecture modelling in Blender
    name: Stýpelas
  byrgen:
    desc: Ghost Theme
    name: Byrgen
  twitter-bg-restorer:
    desc: Firefox/Chrome plugin
    name: Twitter Background Restorer
  geard:
    desc: Indoor Herb Garden
    name: Geard
  hlaf:
    desc: Meal Planning App
    name: Hláf

# general_areas :: Definitions For General Areas
#
# Area definitions should be in the form:
# code:
#   name: Area Name
#   rendering_string: On {date} I worked on {object} for {duration}
#   use_last_objects: false
#
# See https://faereld.readthedocs.io/en/latest/usage/configuration.html#general-areas
# for more information.
general_areas:
  IRL:
    name: Real life engagements (confs/talks/meetups)
    rendering_string: On {date} I was at {object} for {duration}
    use_last_objects: false
  RDG:
    name: Reading
    rendering_string: On {date} I read {object} for {duration}
    use_last_objects: true
  LNG:
    name: Languages
    rendering_string: On {date} I studied {object} for {duration}
    use_last_objects: true
  BLD:
    name: Bouldering
    rendering_string: On {date} I bouldered at {object} for {duration}
    use_last_objects: true
  TSK:
    name: Tasks
    rendering_string: On {date} I worked on {object} for {duration}
    use_last_objects: false
  LRN:
    name: Education
    rendering_string: On {date} I studied {object} for {duration}
    use_last_objects: true
  WRI:
    name: Writing
    rendering_string: On {date} I wrote on {object} for {duration}
    use_last_objects: true

