#!/usr/bin/bash

WORKSPACE=$(pwd)
JLS_BASE="$HOME/tools/java-language-server/org.eclipse.jdt.ls.product/target/repository"
JLS_JAR="$(ls $JLS_BASE/plugins/org.eclipse.equinox.launcher_*.jar)"

java -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.level=ALL \
     -noverify \
     -Xmx1G \
     -jar "$JLS_JAR" \
     -data "$WORKSPACE" \
     -configuration "$JLS_BASE/config_linux"
