---
- name: Verify Mail Folders Exist
  file:
    path: ~/mail/{{ item | basename }}
    state: directory
  loop:
    - autophagy
    - deadcells

- name: Install Mail Tools
  become: true
  package:
    name: "{{ item | basename }}"
    state: present
  loop:
    - isync
    - msmtp
    - neomutt
    - w3m
    - urlscan
