#!/usr/bin/python
# vi:syntax=python

from convertdate import french_republican as fr
from datetime import datetime as dt
from math import floor

mónþas = [
    u'Hærfest',
    u'Mist',
    u'Forst',
    u'Snáw',
    u'Regn',
    u'Wind',
    u'Sǽd',
    u'Blóstm',
    u'Mǽdland',
    u'Ríp',
    u'Hát',
    u'Wæstm',
    u'Wending'
]

def convert_date(date):
    return [date[2], mónþas[date[1]-1], floor(date[0])]

now = dt.now()
anglo_now = convert_date(fr.from_gregorian(now.year, now.month, now.day))
print("{0} // {1}".format(' '.join(map(str, anglo_now)), now.strftime("%H.%M")))
