---
- name: Install Haskell Language Server
  import_tasks: haskell.yaml
  tags:
    - haskell

- name: Install Elm Language Server
  import_tasks: elm.yaml
  tags:
    - elm

- name: Install Python Language Server
  import_tasks: python.yaml
  tags:
    - python
