#!/usr/bin/python
# vi:syntax=python

from convertdate import french_republican as fr
import datetime as dt
from collections import OrderedDict

def roman_year(year):
    numerals = {'M':1000, 'CM':900, 'D':500, 'CD':400,
                'C':100, 'XC':900, 'L':50, 'XL':40,
                'X': 10, 'IX': 9,  'V':5, 'IV':4, 'I':1}
    numerals = OrderedDict(sorted(numerals.items(), key=lambda k: k[1],
                                  reverse=True))
    roman_year = ''
    for numeral in numerals:
        c = int(year/numerals[numeral])
        roman_year += numeral*c
        year -= numerals[numeral]*c
    return roman_year

now = dt.datetime.now()
republican_now = fr.from_gregorian(now.year, now.month, now.day)
formatted = fr.format(republican_now[0], republican_now[1], republican_now[2])
roman_numeral_year = roman_year(republican_now[0])
print("{0} {1} // {2}".format(formatted[:formatted.rfind(' ')],
                                        roman_numeral_year,
                                        now.strftime("%H.%M")))
