---
- name: Verify Sandbox Exists
  file:
    path: ~/sandbox/autophagy
    state: directory
- name: Clone Personal Projects
  git:
    repo: git@github.com:autophagy/{{ item }}
    dest: ~/sandbox/autophagy/{{ item | basename }}
    update: no
  tags:
    - projects
  loop:
   - aerende              # Reminder app
   - ametan               # Scrum poker android app
   - andcwisa             # Solutions to textbook questions
   - byrgen               # Minimalist theme for Ghost
   - datarum              # Custom calendar library
   - faereld              # Time tracker
   - forebodere           # Discord quote bot
   - haefen               # autophagy.io
   - heallreafes          # Talk presentations
   - hlaf                 # Meal planning
   - hraew                # Portfolio site
   - insegel              # RTD theme
   - scieldas             # Repo metadata badges
   - tid                  # Cooking timer tool
   - twitter-bg-restorer  # FF/Chrome addon to set Twitter background
   - wisdomhord           # Flat-file DB
- name: Clone Non-Personal Projects
  git:
    repo: git@github.com:{{ item }}
    dest: ~/sandbox/autophagy/{{ item | basename }}
    update: no
    tags:
     - projects
  loop:
   - psf/black            # Python code formatter
