name: CI
on:
  push:
    branches:
      - master
concurrency:
  group: ci
  cancel-in-progress: true
jobs:
  home-manager-build:
    name: Home Manager Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - mika

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build Home Manager Config
        run: nix build .#homeConfigurations.${{ matrix.user }}.activationPackage

  nixos-build:
    name: NixOS Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - heorot
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build NixOS
        run: nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel

  fmt:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Fmt
        run: nix develop .#ci -c nixpkgs-fmt --check ./
