name: CI
on:
  push:
    branches:
      - master
jobs:
  home-manager-build:
    name: Home Manager Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user:
          - mika

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build Home Manager Config
        run: nix build .#homeConfigurations.${{ matrix.user }}.activationPackage

  nixos-build:
    name: NixOS Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - heorot
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build NixOS
        run: nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel

  fmt:
    name: Nixpkgs Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: Lint
        run: nix-shell -p nixpkgs-fmt --run "find . -name '*.nix' | xargs nixpkgs-fmt --check"
