name: CI
on:
  - push
jobs:
  build:
    name: Home Manager Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: "nixpkgs=channel:nixos-22.05"

      - name: Add Home Manager Channel
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz home-manager
          nix-channel --update

      - name: Link nixpkgs
        run: |
          mkdir -p $HOME/.config
          ln -s $GITHUB_WORKSPACE/nixos/nixpkgs $HOME/.config/nixpkgs

      - name: Install Home Manager
        run: |
          nix-shell -I $HOME/.nix-defexpr/channels '<home-manager>' -A install

  fmt:
    name: Nixpkgs Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: "nixpkgs=channel:nixos-22.05"

      - name: Lint
        run: nix-shell -p nixpkgs-fmt --run "find nixos -name '*.nix' | xargs nixpkgs-fmt --check"
